### ISSUE TITLE
RuntimeError: merge_sort: failed to synchronize: an illegal memory access was encountered

### ISSUE THREAD

**Issue by JisuiWang** [facebookresearch/maskrcnn-benchmark#231]
## ❓ Questions and Help
I just want to train the Faster R-CNN_R_50_C4 model on the VOC2007 dataset. But there is an error I can't figure out:

> Traceback (most recent call last):
  File "tools/train_net.py", line 171, in <module>
    main()
  File "tools/train_net.py", line 164, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 73, in train
    arguments,
  File "/data2/zoro/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 66, in do_train
    loss_dict = model(images, targets)
  File "/home/zoro/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/data2/zoro/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 50, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/zoro/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/data2/zoro/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 100, in forward
    return self._forward_train(anchors, objectness, rpn_box_regression, targets)
  File "/data2/zoro/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 116, in _forward_train
    anchors, objectness, rpn_box_regression, targets
  File "/home/zoro/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/data2/zoro/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/inference.py", line 138, in forward
    sampled_boxes.append(self.forward_for_single_feature_map(a, o, b))
  File "/data2/zoro/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/inference.py", line 118, in forward_for_single_feature_map
    score_field="objectness",
  File "/data2/zoro/maskrcnn-benchmark/maskrcnn_benchmark/structures/boxlist_ops.py", line 27, in boxlist_nms
    keep = _box_nms(boxes, score, nms_thresh)
RuntimeError: merge_sort: failed to synchronize: an illegal memory access was encountered

 
my environment:
ubuntu 18.04
cuda 9.0
cudnn 7.4.1
torch-nightly
gcc 5.5.0
python 3.7(conda)

**Comment by fmassa** [comment]
Hi,

This has been fixed in PyTorch yesterday via https://github.com/pytorch/pytorch/pull/14504 , and should be in the nightly from today or tomorrow.
Can you try updating PyTorch today? This should fix it.

Let me know if the nightly from tomorrow (at most) doesn't fix it.

**Comment by JisuiWang** [comment]
@fmassa Thank you for your quick reply. I'd like to add that I encounter the problem when I try to train the model using a single GPU. I use the statement `CUDA_VISIBLE_DEVICES=2 nohup python -u tools/train_net.py --config-file "configs/e2e_faster_rcnn_R_50_C4_1x_voc.yaml" >voc.out 2>&1 &` at the terminal and I have set a smaller learning rate in the config file. Anyway, I will try to update PyTorch and tell you whether the problem is fixed.

**Comment by fmassa** [comment]
Yes, it is expected to cause the error on both single GPU and multi GPU, but has already been fixed.

**Comment by JisuiWang** [comment]
@fmassa I have updated the PyTorch and now its version is 1.0.0.dev20181129. I try to start the training but a new error occurs:
`nohup: ignoring input
Traceback (most recent call last):
  File "tools/train_net.py", line 18, in <module>
    from maskrcnn_benchmark.engine.inference import inference
  File "/data2/zoro/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 10, in <module>
    from maskrcnn_benchmark.data.datasets.evaluation import evaluate
  File "/data2/zoro/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/__init__.py", line 3, in <module>
    from .coco import coco_evaluation
  File "/data2/zoro/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/coco/__init__.py", line 1, in <module>
    from .coco_eval import do_coco_evaluation
  File "/data2/zoro/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py", line 10, in <module>
    from maskrcnn_benchmark.structures.boxlist_ops import boxlist_iou
  File "/data2/zoro/maskrcnn-benchmark/maskrcnn_benchmark/structures/boxlist_ops.py", line 6, in <module>
    from maskrcnn_benchmark.layers import nms as _box_nms
  File "/data2/zoro/maskrcnn-benchmark/maskrcnn_benchmark/layers/__init__.py", line 8, in <module>
    from .nms import nms
  File "/data2/zoro/maskrcnn-benchmark/maskrcnn_benchmark/layers/nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: /data2/zoro/maskrcnn-benchmark/maskrcnn_benchmark/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at4cuda20getCurrentCUDAStreamEl`
which is the identical to [#226](https://github.com/facebookresearch/maskrcnn-benchmark/issues/226).

**Comment by lbin** [comment]
@fmassa I still have this problem. My torch version is dev20181213.

**Comment by fmassa** [comment]
Hi @lbin,

Did you delete the `build` folder from `maskrcnn-benchmark` and recompiled it?

**Comment by xxl1995** [comment]
When the lr is smaller ,the question will get over. Maybe the Nan cause it.
