### ISSUE TITLE
Shuffle = False throws error on multi-gpu

### ISSUE THREAD

**Issue by akshitac8** [facebookresearch/maskrcnn-benchmark#474]
when during training time we set shuffle = False, The grouped_batch_sampler through an error of 
```
IndexError: index 0 is out of bounds for dimension 0 with size 0
```

**Comment by akshitac8** [comment]
Also, It gives **out of memory** error when trained on multi-GPU but runs smoothly on a single GPU with slow speed.

**Comment by fmassa** [comment]
This is probably a corner case in the `grouped_batch_sampler`, as there might be no elements for one of the groups.

My recommendation here would be to shuffle the dataset. I'm not 100% sure where this error happens, but contributions are welcome

**Comment by akshitac8** [comment]
Even if I shuffle the data it gives out of memory when trained on multi-GPU but runs smoothly on a single GPU with slow speed.

**Comment by fmassa** [comment]
I don't understand why it would give out of memory.
Do you have a custom version of `maskrcnn-benchmark`?

**Comment by akshitac8** [comment]
I have the one on the default branch

**Comment by fmassa** [comment]
Are you training on COCO or on a custom dataset? I'm trying to understand how this is happening

**Comment by akshitac8** [comment]
I was able to solve the cuda out of memory error as it was because of the memory leak. But shuffle = False still remains an error.
I am training on custom dataset but the annotation for the custom dataset is similar to coco.

**Comment by fmassa** [comment]
I think there is a corner case in `shuffle=False` that is not handled properly.

From the error message, it might be the case that there are not enough elements in one group. For example, if all the landscape images are consecutive, followed by all portrait images maybe?

**Comment by kakaluote** [comment]
i met this problem but shuffle=True. this happened when i change a dataset. help to solve it please

**Comment by kakaluote** [comment]
in my case, group_ids only have one 1,others are 0, then groups is [0,1], 
` clusters = [(self.group_ids == i) & mask for i in self.groups]`
when some random, clusters will be [[1,1,1.....],[] ] , and the error happened
