### ISSUE TITLE
Race Condition -> RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/nms.cu:103

### ISSUE THREAD

**Issue by IssamLaradji** [facebookresearch/maskrcnn-benchmark#499]
## 🐛 Bug

When my maskrcnn's parameters `requires_grad` is False, I get an error in the inference stage due to `nms`. This didn't happen in last month's version of this repo.

## To Reproduce
I run the following command for a CityScapes batch.
```
for p in mrcnn.parameters():
     p.requires_grad = False

mrcnn.eval()
predictions = mrcnn(image_list)
```
Error that I get,
```
    result = self.forward(*input, **kwargs)
  File "/mnt/home/issam/Research_Ground/domain_adaptation/models/base_models/adv_mrcnn.py", line 242, in forward
    x, result, detector_losses = self.roi_heads(features, proposals, targets)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/home/issam/Research_Ground/domain_adaptation/models/maskrcnn/heads.py", line 26, in forward
    x, detections, loss_box = self.box(features, proposals, targets)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/box_head/box_head.py", line 52, in forward
    result = self.post_processor((class_logits, box_regression), proposals)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/box_head/inference.py", line 82, in forward
    boxlist = self.filter_results(boxlist, num_classes)
  File "/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/box_head/inference.py", line 126, in filter_results
    boxlist_for_class, self.nms
  File "/maskrcnn-benchmark/maskrcnn_benchmark/structures/boxlist_ops.py", line 27, in boxlist_nms 
    keep = _box_nms(boxes, score, nms_thresh)
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/nms.cu:103
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /maskrcnn-benchmark/maskrcnn_benchmark/structures/boxlist_ops.py(27)boxlist_nms()
     26     score = boxlist.get_field(score_field)
---> 27     keep = _box_nms(boxes, score, nms_thresh)
     28     if max_proposals > 0:
```

## Environment

Numpy: 1.15.4 
CUDA: 9.0.176 
Pytroch: 1.0.1.post2 
CUDNN: 7402

**Comment by IssamLaradji** [comment]
I believe it is a race condition@fmassa, I can print `torch.zeros(5).cuda(0)`
before calling the line,
```
concat_boxes = torch.cat([a.bbox for a in boxes], dim=0)
```
in  `maskrcnn_benchmark/modeling/roi_heads/box_head/inference.py`
but after that line calling  `torch.zeros(5).cuda(0)`  (without waiting), causes the issue `RuntimeError: CUDA error: an illegal memory access was encountered`

Note that `boxes` is in GPU 1.

**Comment by fmassa** [comment]
I think that the error is not in `nms`, but might happen before. Can you run your inference code with `CUDA_LAUNCH_BLOCKING=1 python tools/test_net.py --etc` and see where the error is raised?

**Comment by IssamLaradji** [comment]
You are right, I am still not sure where the bug came from :(, so I just reverted back to my older code base went to a different docker and things are working as expected. And it was happening very arbitrarily (I can't reproduce it anymore).
This started also after using `nn.DistributedDataParallel` but I am not sure if it contributed to it.

 I can close this issue until it happens again.

**Comment by fmassa** [comment]
@IssamLaradji maybe you had a bugged PyTorch version?
There was a version of PyTorch nightly that had a bug, but it has been fixed since then

**Comment by IssamLaradji** [comment]
@fmassa I found the reason why this happened. It was because I had  a pytorch `dataset` that also calls `__get_item__` of another dataset and that caused `illegal memory access` issues with the dataloader.

**Comment by fmassa** [comment]
I think the illegal memory access was in the other dataset then?

**Comment by ruiyuanlu** [comment]
Hi, I met the same issue. I found that nms.cu initialize its threads on GPU-0 by default, and will raise such illegal memory access error when boxes is on other GPUs. Any idea to fix this ?

**Comment by IssamLaradji** [comment]
In my case, the issue was that I was using python multithreading to run two threads, one for training and one for validation. I fixed this by using multiprocessing instead of multithreading.

Are you running multiple threads?

**Comment by ruiyuanlu** [comment]
> In my case, the issue was that I was using python multithreading to run two threads, one for training and one for validation. I fixed this by using multiprocessing instead of multithreading.
> 
> Are you running multiple threads?

No. Actually, I tried to compile only nms.cu, no more code included, and found this issue.

**Comment by AlenUbuntu** [comment]
> Hi, I met the same issue. I found that nms.cu initialize its threads on GPU-0 by default, and will raise such illegal memory access error when input tensor `boxes` is on other GPUs. Any idea to fix this ?

Yes, If I tried to assign the model to a specific GPU, e.g., cuda:1, the error occurs

**Comment by Vimos** [comment]
I am encountering a similar problem. I am using multiple GPUs with multiprocessing. 

```
  File "/opt/conda/lib/python3.7/site-packages/maskrcnn_benchmark-0.1-py3.7-linux-x86_64.egg/maskrcnn_benchmark/modeling/rpn/inference.py", line 135, in forward
    sampled_boxes.append(self.forward_for_single_feature_map(a, o, b))
  File "/opt/conda/lib/python3.7/site-packages/maskrcnn_benchmark-0.1-py3.7-linux-x86_64.egg/maskrcnn_benchmark/modeling/rpn/inference.py", line 115, in forward_for_single_feature_map
    score_field="objectness",
  File "/opt/conda/lib/python3.7/site-packages/maskrcnn_benchmark-0.1-py3.7-linux-x86_64.egg/maskrcnn_benchmark/structures/boxlist_ops.py", line 27, in boxlist_nms
    keep = _box_nms(boxes, score, nms_thresh)
RuntimeError: cuda runtime error (700) : an illegal memory access was encountered at /src/vqa-maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/nms.cu:103
```

**Comment by np-ftrwei** [comment]
Why be in a hurry to close? Anyway.. This issue keeps happening. Running a MaskRCNN benchmark, what is worse is when CUDA_LAUNCH_BLOCKING=1 turned on, the issue goes away.
Bad old days of C and its memory problems!

**Comment by yangxu351** [comment]
> I am encountering a similar problem. I am using multiple GPUs with multiprocessing.
> 
> ```
>   File "/opt/conda/lib/python3.7/site-packages/maskrcnn_benchmark-0.1-py3.7-linux-x86_64.egg/maskrcnn_benchmark/modeling/rpn/inference.py", line 135, in forward
>     sampled_boxes.append(self.forward_for_single_feature_map(a, o, b))
>   File "/opt/conda/lib/python3.7/site-packages/maskrcnn_benchmark-0.1-py3.7-linux-x86_64.egg/maskrcnn_benchmark/modeling/rpn/inference.py", line 115, in forward_for_single_feature_map
>     score_field="objectness",
>   File "/opt/conda/lib/python3.7/site-packages/maskrcnn_benchmark-0.1-py3.7-linux-x86_64.egg/maskrcnn_benchmark/structures/boxlist_ops.py", line 27, in boxlist_nms
>     keep = _box_nms(boxes, score, nms_thresh)
> RuntimeError: cuda runtime error (700) : an illegal memory access was encountered at /src/vqa-maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/nms.cu:103
> ```

have you resolved this issue? I'm using single GPU, but the same problem.

**Comment by yangxu351** [comment]
> Hi, I met the same issue. I found that nms.cu initialize its threads on GPU-0 by default, and will raise such illegal memory access error when input tensor `boxes` is on other GPUs. Any idea to fix this ?

I specified the device "cuda:0", and it works.
