### ISSUE TITLE
CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by nicolasCruzW21** [facebookresearch/maskrcnn-benchmark#688]
Hello, I am trying to train the model on the COCO dataset, however I get a cuDNN error, any Idea of what the problem might be?

CUDA 9.0
cuDNN 7.5 for cuda 9.0
RTX 2080 ti

from the console:

index created!
2019-04-17 12:08:49,591 maskrcnn_benchmark.trainer INFO: Start training
Traceback (most recent call last):
  File "tools/train_net.py", line 174, in <module>
    main()
  File "tools/train_net.py", line 167, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 73, in train
    arguments,
  File "/home/nicolas/instanceSegmentation/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 76, in do_train
    losses.backward()
  File "/home/nicolas/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/nicolas/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

Thank you for your help!

**Comment by nicolasCruzW21** [comment]
Solved it by installing all again with cuda 10. It seems cuda 9.0 doesn't work well with Turing architecture
