### ISSUE TITLE
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1549635019666/work/torch/lib/c10d/ProcessGroupNCCL.cpp:388, invalid argument

### ISSUE THREAD

**Issue by ChenJoya** [facebookresearch/maskrcnn-benchmark#699]
## 🐛 Bug

**Hi @fmassa , when I adopt multi-gpu training, it seems the NCCL error appears.**
```Traceback (most recent call last):
  File "tools/train_net.py", line 174, in <module>
    main()
  File "tools/train_net.py", line 144, in main
    synchronize()
  File "/home/chenjoya/projects/maskrcnn-sampler/maskrcnn_benchmark/utils/comm.py", line 45, in synchronize
    dist.barrier()
  File "/home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1177, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1549635019666/work/torch/lib/c10d/ProcessGroupNCCL.cpp:388, invalid argument
Traceback (most recent call last):
  File "tools/train_net.py", line 174, in <module>
    main()
  File "tools/train_net.py", line 144, in main
    synchronize()
  File "/home/chenjoya/projects/maskrcnn-sampler/maskrcnn_benchmark/utils/comm.py", line 45, in synchronize
    dist.barrier()
  File "/home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1177, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1549635019666/work/torch/lib/c10d/ProcessGroupNCCL.cpp:388, invalid argument
```
## To Reproduce
The training script: 
```
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 tools/train_net.py --config-file configs/e2e_faster_rcnn_R_50_FPN_1x.yaml
```

## Environment
pytorch 1.0.1
CUDA 9.0
NVIDIA-SMI 390.87
GCC 4.9.2-6
Linux version 3.10.0-862.14.4.el7.x86_64

Thanks for your attention ! ^ ^

**Comment by ChenJoya** [comment]
I also tried pytorch-nightly-1.0.0, the bug is also existing T T

**Comment by ChenJoya** [comment]
Please help me @fmassa, thank you.
The bug makes me feel so bad, when I try to train on 8 GPUS and there are another ..
```
Traceback (most recent call last):
  File "tools/train_net.py", line 174, in <module>
    main()
  File "tools/train_net.py", line 144, in main
    synchronize()
  File "/home/chenjoya/projects/maskrcnn-sampler/maskrcnn_benchmark/utils/comm.py", line 45, in synchronize
    dist.barrier()
  File "/home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1177, in barrier
    work = _default_pg.barrier()
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable (malloc at /opt/conda/conda-bld/pytorch_1549635019666/work/aten/src/THC/THCCachingAllocator.cpp:233)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7f6a6057fcf5 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1227d90 (0x7f6a6484fd90 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #2: <unknown function> + 0x1228d4a (0x7f6a64850d4a in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #3: at::native::empty_cuda(c10::ArrayRef<long>, at::TensorOptions const&) + 0x2d6 (0x7f6a65c3da36 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #4: at::CUDAByteType::empty(c10::ArrayRef<long>, at::TensorOptions const&) const + 0x4d (0x7f6a646edecd in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #5: c10d::ProcessGroupNCCL::barrier(c10d::BarrierOptions const&) + 0x2d4 (0x7f6a81d2a644 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x60a543 (0x7f6a81c9c543 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x111af6 (0x7f6a817a3af6 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #8: _PyMethodDef_RawFastCallKeywords + 0x264 (0x55a32ba986e4 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #9: _PyCFunction_FastCallKeywords + 0x21 (0x55a32ba98801 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #10: _PyEval_EvalFrameDefault + 0x537e (0x55a32baf47ae in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #11: <unknown function> + 0x178620 (0x55a32ba97620 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #12: _PyEval_EvalFrameDefault + 0x4aa9 (0x55a32baf3ed9 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #13: _PyFunction_FastCallKeywords + 0xfb (0x55a32ba9779b in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #14: _PyEval_EvalFrameDefault + 0x416 (0x55a32baef846 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #15: _PyFunction_FastCallKeywords + 0xfb (0x55a32ba9779b in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #16: _PyEval_EvalFrameDefault + 0x416 (0x55a32baef846 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #17: _PyEval_EvalCodeWithName + 0x2f9 (0x55a32ba354f9 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #18: PyEval_EvalCodeEx + 0x44 (0x55a32ba363c4 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #19: PyEval_EvalCode + 0x1c (0x55a32ba363ec in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #20: <unknown function> + 0x22f874 (0x55a32bb4e874 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #21: PyRun_FileExFlags + 0xa1 (0x55a32bb58b81 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #22: PyRun_SimpleFileExFlags + 0x1c3 (0x55a32bb58d73 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #23: <unknown function> + 0x23ae5f (0x55a32bb59e5f in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #24: _Py_UnixMain + 0x3c (0x55a32bb59f7c in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #25: __libc_start_main + 0xf5 (0x7f6a98f023d5 in /lib64/libc.so.6)
frame #26: <unknown function> + 0x1e0122 (0x55a32baff122 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
Traceback (most recent call last):

  File "tools/train_net.py", line 174, in <module>
    main()
  File "tools/train_net.py", line 144, in main
Traceback (most recent call last):
  File "tools/train_net.py", line 174, in <module>
    synchronize()
  File "/home/chenjoya/projects/maskrcnn-sampler/maskrcnn_benchmark/utils/comm.py", line 45, in synchronize
    dist.barrier()
  File "/home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1177, in barrier
    Traceback (most recent call last):
work = _default_pg.barrier()
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable (malloc at /opt/conda/conda-bld/pytorch_1549635019666/work/aten/src/THC/THCCachingAllocator.cpp:233)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7f7249dafcf5 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1227d90 (0x7f724e07fd90 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #2: <unknown function> + 0x1228d4a (0x7f724e080d4a in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #3: at::native::empty_cuda(c10::ArrayRef<long>, at::TensorOptions const&) + 0x2d6 (0x7f724f46da36 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #4: at::CUDAByteType::empty(c10::ArrayRef<long>, at::TensorOptions const&) const + 0x4d (0x7f724df1decd in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #5: c10d::ProcessGroupNCCL::barrier(c10d::BarrierOptions const&) + 0x2d4 (0x7f726b55a644 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x60a543 (0x7f726b4cc543 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x111af6 (0x7f726afd3af6 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #8: _PyMethodDef_RawFastCallKeywords + 0x264 (0x561e17b4e6e4 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #9: _PyCFunction_FastCallKeywords + 0x21 (0x561e17b4e801 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #10: _PyEval_EvalFrameDefault + 0x537e (0x561e17baa7ae in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #11: <unknown function> + 0x178620 (0x561e17b4d620 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #12: _PyEval_EvalFrameDefault + 0x4aa9 (0x561e17ba9ed9 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #13: _PyFunction_FastCallKeywords + 0xfb (0x561e17b4d79b in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #14: _PyEval_EvalFrameDefault + 0x416 (0x561e17ba5846 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #15: _PyFunction_FastCallKeywords + 0xfb (0x561e17b4d79b in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #16: _PyEval_EvalFrameDefault + 0x416 (0x561e17ba5846 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #17: _PyEval_EvalCodeWithName + 0x2f9 (0x561e17aeb4f9 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #18: PyEval_EvalCodeEx + 0x44 (0x561e17aec3c4 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #19: PyEval_EvalCode + 0x1c (0x561e17aec3ec in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #20: <unknown function> + 0x22f874 (0x561e17c04874 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #21: PyRun_FileExFlags + 0xa1 (0x561e17c0eb81 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #22: PyRun_SimpleFileExFlags + 0x1c3 (0x561e17c0ed73 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #23: <unknown function> + 0x23ae5f (0x561e17c0fe5f in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #24: _Py_UnixMain + 0x3c (0x561e17c0ff7c in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #25: __libc_start_main + 0xf5 (0x7f72827323d5 in /lib64/libc.so.6)
frame #26: <unknown function> + 0x1e0122 (0x561e17bb5122 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
  File "tools/train_net.py", line 174, in <module>

    main()
  File "tools/train_net.py", line 144, in main
    synchronize()
  File "/home/chenjoya/projects/maskrcnn-sampler/maskrcnn_benchmark/utils/comm.py", line 45, in synchronize
    main()
  File "tools/train_net.py", line 144, in main
    dist.barrier()
  File "/home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1177, in barrier
Traceback (most recent call last):
  File "tools/train_net.py", line 174, in <module>
    synchronize()
  File "/home/chenjoya/projects/maskrcnn-sampler/maskrcnn_benchmark/utils/comm.py", line 45, in synchronize
    dist.barrier()
  File "/home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1177, in barrier
    main()
  File "tools/train_net.py", line 144, in main
    work = _default_pg.barrier()
    synchronize()
  File "/home/chenjoya/projects/maskrcnn-sampler/maskrcnn_benchmark/utils/comm.py", line 45, in synchronize
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable (malloc at /opt/conda/conda-bld/pytorch_1549635019666/work/aten/src/THC/THCCachingAllocator.cpp:233)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7fe95e36ccf5 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1227d90 (0x7fe96263cd90 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #2: <unknown function> + 0x1228d4a (0x7fe96263dd4a in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #3: at::native::empty_cuda(c10::ArrayRef<long>, at::TensorOptions const&) + 0x2d6 (0x7fe963a2aa36 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #4: at::CUDAByteType::empty(c10::ArrayRef<long>, at::TensorOptions const&) const + 0x4d (0x7fe9624daecd in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #5: c10d::ProcessGroupNCCL::barrier(c10d::BarrierOptions const&) + 0x2d4 (0x7fe97fb17644 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x60a543 (0x7fe97fa89543 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x111af6 (0x7fe97f590af6 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #8: _PyMethodDef_RawFastCallKeywords + 0x264 (0x556cc71336e4 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #9: _PyCFunction_FastCallKeywords + 0x21 (0x556cc7133801 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #10: _PyEval_EvalFrameDefault + 0x537e (0x556cc718f7ae in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #11: <unknown function> + 0x178620 (0x556cc7132620 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #12: _PyEval_EvalFrameDefault + 0x4aa9 (0x556cc718eed9 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #13: _PyFunction_FastCallKeywords + 0xfb (0x556cc713279b in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #14: _PyEval_EvalFrameDefault + 0x416 (0x556cc718a846 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #15: _PyFunction_FastCallKeywords + 0xfb (0x556cc713279b in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #16: _PyEval_EvalFrameDefault + 0x416 (0x556cc718a846 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #17: _PyEval_EvalCodeWithName + 0x2f9 (0x556cc70d04f9 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #18: PyEval_EvalCodeEx + 0x44 (0x556cc70d13c4 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #19: PyEval_EvalCode + 0x1c (0x556cc70d13ec in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #20: <unknown function> + 0x22f874 (0x556cc71e9874 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #21: PyRun_FileExFlags + 0xa1 (0x556cc71f3b81 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #22: PyRun_SimpleFileExFlags + 0x1c3 (0x556cc71f3d73 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #23: <unknown function> + 0x23ae5f (0x556cc71f4e5f in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #24: _Py_UnixMain + 0x3c (0x556cc71f4f7c in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #25: __libc_start_main + 0xf5 (0x7fe996cef3d5 in /lib64/libc.so.6)
frame #26: <unknown function> + 0x1e0122 (0x556cc719a122 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
    
dist.barrier()
  File "/home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1177, in barrier
    work = _default_pg.barrier()
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable (malloc at /opt/conda/conda-bld/pytorch_1549635019666/work/aten/src/THC/THCCachingAllocator.cpp:233)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7f9964255cf5 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1227d90 (0x7f9968525d90 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #2: <unknown function> + 0x1228d4a (0x7f9968526d4a in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #3: at::native::empty_cuda(c10::ArrayRef<long>, at::TensorOptions const&) + 0x2d6 (0x7f9969913a36 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #4: at::CUDAByteType::empty(c10::ArrayRef<long>, at::TensorOptions const&) const + 0x4d (0x7f99683c3ecd in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #5: c10d::ProcessGroupNCCL::barrier(c10d::BarrierOptions const&) + 0x2d4 (0x7f9985a00644 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x60a543 (0x7f9985972543 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x111af6 (0x7f9985479af6 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #8: _PyMethodDef_RawFastCallKeywords + 0x264 (0x558f92aab6e4 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #9: _PyCFunction_FastCallKeywords + 0x21 (0x558f92aab801 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #10: _PyEval_EvalFrameDefault + 0x537e (0x558f92b077ae in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #11: <unknown function> + 0x178620 (0x558f92aaa620 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #12: _PyEval_EvalFrameDefault + 0x4aa9 (0x558f92b06ed9 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #13: _PyFunction_FastCallKeywords + 0xfb (0x558f92aaa79b in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #14: _PyEval_EvalFrameDefault + 0x416 (0x558f92b02846 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #15: _PyFunction_FastCallKeywords + 0xfb (0x558f92aaa79b in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #16: _PyEval_EvalFrameDefault + 0x416 (0x558f92b02846 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #17: _PyEval_EvalCodeWithName + 0x2f9 (0x558f92a484f9 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #18: PyEval_EvalCodeEx + 0x44 (0x558f92a493c4 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #19: PyEval_EvalCode + 0x1c (0x558f92a493ec in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #20: <unknown function> + 0x22f874 (0x558f92b61874 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #21: PyRun_FileExFlags + 0xa1 (0x558f92b6bb81 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #22: PyRun_SimpleFileExFlags + 0x1c3 (0x558f92b6bd73 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #23: <unknown function> + 0x23ae5f (0x558f92b6ce5f in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #24: _Py_UnixMain + 0x3c (0x558f92b6cf7c in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #25: __libc_start_main + 0xf5 (0x7f999cbd83d5 in /lib64/libc.so.6)
frame #26: <unknown function> + 0x1e0122 (0x558f92b12122 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)

    work = _default_pg.barrier()
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable (malloc at /opt/conda/conda-bld/pytorch_1549635019666/work/aten/src/THC/THCCachingAllocator.cpp:233)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7fcfd7506cf5 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1227d90 (0x7fcfdb7d6d90 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #2: <unknown function> + 0x1228d4a (0x7fcfdb7d7d4a in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #3: at::native::empty_cuda(c10::ArrayRef<long>, at::TensorOptions const&) + 0x2d6 (0x7fcfdcbc4a36 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #4: at::CUDAByteType::empty(c10::ArrayRef<long>, at::TensorOptions const&) const + 0x4d (0x7fcfdb674ecd in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #5: c10d::ProcessGroupNCCL::barrier(c10d::BarrierOptions const&) + 0x2d4 (0x7fcff8cb1644 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x60a543 (0x7fcff8c23543 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x111af6 (0x7fcff872aaf6 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #8: _PyMethodDef_RawFastCallKeywords + 0x264 (0x55b174d946e4 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #9: _PyCFunction_FastCallKeywords + 0x21 (0x55b174d94801 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #10: _PyEval_EvalFrameDefault + 0x537e (0x55b174df07ae in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #11: <unknown function> + 0x178620 (0x55b174d93620 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #12: _PyEval_EvalFrameDefault + 0x4aa9 (0x55b174defed9 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #13: _PyFunction_FastCallKeywords + 0xfb (0x55b174d9379b in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #14: _PyEval_EvalFrameDefault + 0x416 (0x55b174deb846 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #15: _PyFunction_FastCallKeywords + 0xfb (0x55b174d9379b in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #16: _PyEval_EvalFrameDefault + 0x416 (0x55b174deb846 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #17: _PyEval_EvalCodeWithName + 0x2f9 (0x55b174d314f9 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #18: PyEval_EvalCodeEx + 0x44 (0x55b174d323c4 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #19: PyEval_EvalCode + 0x1c (0x55b174d323ec in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #20: <unknown function> + 0x22f874 (0x55b174e4a874 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #21: PyRun_FileExFlags + 0xa1 (0x55b174e54b81 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #22: PyRun_SimpleFileExFlags + 0x1c3 (0x55b174e54d73 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #23: <unknown function> + 0x23ae5f (0x55b174e55e5f in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #24: _Py_UnixMain + 0x3c (0x55b174e55f7c in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #25: __libc_start_main + 0xf5 (0x7fd00fe893d5 in /lib64/libc.so.6)
frame #26: <unknown function> + 0x1e0122 (0x55b174dfb122 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)

Traceback (most recent call last):
  File "tools/train_net.py", line 174, in <module>
    main()
  File "tools/train_net.py", line 144, in main
    synchronize()
  File "/home/chenjoya/projects/maskrcnn-sampler/maskrcnn_benchmark/utils/comm.py", line 45, in synchronize
    dist.barrier()
  File "/home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1177, in barrier
    work = _default_pg.barrier()
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable (malloc at /opt/conda/conda-bld/pytorch_1549635019666/work/aten/src/THC/THCCachingAllocator.cpp:233)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7f5820165cf5 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1227d90 (0x7f5824435d90 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #2: <unknown function> + 0x1228d4a (0x7f5824436d4a in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #3: at::native::empty_cuda(c10::ArrayRef<long>, at::TensorOptions const&) + 0x2d6 (0x7f5825823a36 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #4: at::CUDAByteType::empty(c10::ArrayRef<long>, at::TensorOptions const&) const + 0x4d (0x7f58242d3ecd in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #5: c10d::ProcessGroupNCCL::barrier(c10d::BarrierOptions const&) + 0x2d4 (0x7f5841910644 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x60a543 (0x7f5841882543 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x111af6 (0x7f5841389af6 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #8: _PyMethodDef_RawFastCallKeywords + 0x264 (0x5577a916c6e4 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #9: _PyCFunction_FastCallKeywords + 0x21 (0x5577a916c801 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #10: _PyEval_EvalFrameDefault + 0x537e (0x5577a91c87ae in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #11: <unknown function> + 0x178620 (0x5577a916b620 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #12: _PyEval_EvalFrameDefault + 0x4aa9 (0x5577a91c7ed9 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #13: _PyFunction_FastCallKeywords + 0xfb (0x5577a916b79b in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #14: _PyEval_EvalFrameDefault + 0x416 (0x5577a91c3846 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #15: _PyFunction_FastCallKeywords + 0xfb (0x5577a916b79b in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #16: _PyEval_EvalFrameDefault + 0x416 (0x5577a91c3846 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #17: _PyEval_EvalCodeWithName + 0x2f9 (0x5577a91094f9 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #18: PyEval_EvalCodeEx + 0x44 (0x5577a910a3c4 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #19: PyEval_EvalCode + 0x1c (0x5577a910a3ec in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #20: <unknown function> + 0x22f874 (0x5577a9222874 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #21: PyRun_FileExFlags + 0xa1 (0x5577a922cb81 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #22: PyRun_SimpleFileExFlags + 0x1c3 (0x5577a922cd73 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #23: <unknown function> + 0x23ae5f (0x5577a922de5f in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #24: _Py_UnixMain + 0x3c (0x5577a922df7c in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)
frame #25: __libc_start_main + 0xf5 (0x7f5858ae83d5 in /lib64/libc.so.6)
frame #26: <unknown function> + 0x1e0122 (0x5577a91d3122 in /home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/bin/python)

Traceback (most recent call last):
  File "tools/train_net.py", line 174, in <module>
    main()
  File "tools/train_net.py", line 144, in main
    synchronize()
  File "/home/chenjoya/projects/maskrcnn-sampler/maskrcnn_benchmark/utils/comm.py", line 45, in synchronize
    dist.barrier()
  File "/home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1177, in barrier
    work = _default_pg.barrier()
RuntimeError: Broken pipe
Traceback (most recent call last):
  File "tools/train_net.py", line 174, in <module>
    main()
  File "tools/train_net.py", line 144, in main
    synchronize()
  File "/home/chenjoya/projects/maskrcnn-sampler/maskrcnn_benchmark/utils/comm.py", line 45, in synchronize
    dist.barrier()
  File "/home/chenjoya/opt/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1177, in barrier
    work = _default_pg.barrier()
RuntimeError: Broken pipe
```

**Comment by djiajunustc** [comment]
@fmassa Hi, I met a similar bug and info tells:

traceback (most recent call last):
  File "/userhome/detection/codes/maskrcnn-benchmark-custom/tools/train_net.py", line 186, in <module>
    main()
  File "/userhome/detection/codes/maskrcnn-benchmark-custom/tools/train_net.py", line 156, in main
    synchronize()
  File "/userhome/detection/codes/maskrcnn-benchmark-custom/maskrcnn_benchmark/utils/comm.py", line 45, in synchronize
    dist.barrier()
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1240, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch-nightly_1556168966744/work/torch/lib/c10d/ProcessGroupNCCL.cpp:$
46, internal error

This error occurs in titan V. I run the same code with the same docker image on GTX 1080ti, it works well.

Thanks a lot !

**Comment by SpongebBob** [comment]
same issue, sometimes deadlock...

**Comment by ChenJoya** [comment]
Hi @SpongebBob @djiajunustc , thanks for your attention to this problem.

The problem occurs due to the insufficient CPU resources (e.g. the maximum number of threads, RAM memory). 

For me, after increasing the number of restricted threads, it works.

**Comment by SpongebBob** [comment]
> Hi @SpongebBob @djiajunustc , thanks for your attention to this problem.
> 
> The problem occurs due to the insufficient CPU resources (e.g. the maximum number of threads, RAM memory).
> 
> For me, after increasing the number of restricted threads, it works.

I use 30 cpus and 4gpus. I don't know if it is same as your issue.

**Comment by florence27** [comment]
Hi @SpongebBob I met the same error, running on 8GPUs and 10CPUs, did you resolve it by any chance?
