### ISSUE TITLE
apex install error: lib64/libcudnn.so.7/include: Not a directory

### ISSUE THREAD

**Issue by greatgoldfish** [facebookresearch/maskrcnn-benchmark#955]
I followed the INSTALL.md on the apex step, and when I tried
`python setup.py --cuda_ext --cpp_ext`

I get the following error
`error: /usr/local/cuda/lib64/libcudnn.so.7/include: Not a directory`

I have CUDA9, Ubuntu 16.04.11, gcc 5.4.0. I'm not sure how to fix it. I even tried just
`python setup.py install`
but the same error occurred. Thanks for the help.

**Comment by SkeletonOne** [comment]
@greatgoldfish  Have you solved this problem yet? Cuz I met the same problem.

**Comment by lingbo666** [comment]
@SkeletonOne @greatgoldfish  Hi, I am a freshman in this part.Have you solved it?  I also met this problem which makes me terrible.  I well be appreciated!

**Comment by SkeletonOne** [comment]
I changed my cudnn version to 7.0.5 and delete the line of cudnn path in bashrc.Problem Solved------------------ Original ------------------From: lingbo666  <notifications@github.com>Date: Sat,Oct 12,2019 5:11 PMTo: facebookresearch/maskrcnn-benchmark <maskrcnn-benchmark@noreply.github.com>Cc: SkeletonOne <lxy12350@126.com>, Mention <mention@noreply.github.com>Subject: Re: [facebookresearch/maskrcnn-benchmark] apex install error:lib64/libcudnn.so.7/include: Not a directory (#955)@SkeletonOne @greatgoldfish  Hi, I am a freshman in this part.Have you solved it?  I also met this problem which makes me terrible.  I well be appreciated!

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/facebookresearch/maskrcnn-benchmark/issues/955?email_source=notifications\u0026email_token=AHF4ZZ2YHRFWRTVOCBGWYP3QOGIEVA5CNFSM4H6XV3VKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBB2QRI#issuecomment-541304901",
"url": "https://github.com/facebookresearch/maskrcnn-benchmark/issues/955?email_source=notifications\u0026email_token=AHF4ZZ2YHRFWRTVOCBGWYP3QOGIEVA5CNFSM4H6XV3VKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBB2QRI#issuecomment-541304901",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by lingbo666** [comment]
@SkeletonOne I will try it , thanks a lot~

**Comment by anl13** [comment]
https://github.com/facebookresearch/maskrcnn-benchmark/issues/1131#issuecomment-545445005 
This issue may help you

**Comment by lingbo666** [comment]
@anl13  Thanks,i will try it .
